                                                !!INGREIDENTS YOU NEDD!!
                                                           ⇊
⇛125g butter, chopped

⇛2 teaspoons instant coffee powder

⇛3/4 cup (185ml) water

⇛100g good-quality dark cooking chocolate, chopped

⇛1 cup (200g) brown sugar

⇛1/2 cup (75g) self-raising flour

⇛1/2 cup (75g) plain flour

⇛1/4 cup (30g) cocoa powder

⇛1/4 cup (30g) almond meal

⇛egg, lightly whisked

⇛Pink and silver cachous, to decorate